In [1]:
import cv2
from PIL import Image
import json
import torch
import numpy as np
from model.YOLOV8 import YOLOv8_face
from model.dan import FERModel
from torchvision import transforms

parameterRead=None
with open('config.json') as f:
  parameterRead = json.load(f)
Yolodefine=parameterRead['Yolov8']
Dandefine=parameterRead['Dan']
device_id=parameterRead['DEVICE']
DEVICE=torch.device(device_id)


In [3]:
# Initialize YOLOv8_face object detector
YOLOv8_face_detector = YOLOv8_face(Yolodefine['modelpath'], conf_thres=Yolodefine['confThreshold'], iou_thres=Yolodefine['nmsThreshold'])
Fermodel=FERModel(Dandefine)


cap = cv2.VideoCapture(0)
while(True):
    # 一帧一帧捕捉
    ret, srcimg = cap.read()
    boxes, scores, classids, kpts = YOLOv8_face_detector.detect(srcimg)
    #crop_img=YOLOv8_face_detector.crop_detections(srcimg,boxes,scores,kpts)
    #fer="None"
    #if crop_img is not None:
    img=Image.fromarray(cv2.cvtColor(srcimg,cv2.COLOR_BGR2RGB))
    dstimg=Fermodel.detect(img,boxes)
    #  print(fer)
    # 显示返回的每帧
    #dstimg = YOLOv8_face_detector.draw_detections(srcimg, boxes,fer)
    cv2.imshow('frame',dstimg)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cv2.destroyAllWindows()

tensor([[-1.0749, -1.2610, -3.5273,  0.4347,  4.5693,  0.7156, -0.0961]])
tensor([[-0.7675, -1.3767, -3.4080,  0.8625,  4.5498,  0.0823, -0.0484]])
tensor([[-0.8737, -1.3075, -3.2527,  0.5326,  4.4220,  0.2729,  0.1900]])
tensor([[-0.8152, -0.7292, -3.7566,  0.2775,  3.1363,  1.2386, -0.4645]])
tensor([[-0.7094, -0.4836, -3.8827,  0.1469,  3.2773,  1.1406, -0.5310]])
tensor([[-0.9889, -0.7174, -3.6402,  0.3687,  4.1095,  0.5834, -0.5027]])
tensor([[-0.8378, -1.3987, -3.3722,  0.6759,  4.0486,  0.2081,  0.3550]])
tensor([[-0.9989, -1.4421, -3.3432,  0.7150,  4.5789,  0.2384,  0.3331]])
tensor([[-0.6130, -1.0371, -3.4278,  0.2330,  4.1371,  0.2705,  0.2259]])
tensor([[-0.5857, -1.0600, -3.2800,  0.4580,  4.2041, -0.0498,  0.1901]])
tensor([[-0.4049, -1.2072, -3.1693,  0.3274,  4.4941, -0.0756,  0.3933]])
tensor([[-0.8019, -1.0330, -3.4975,  0.5149,  4.3046, -0.0774,  0.2089]])
tensor([[-0.5902, -1.0740, -3.1675,  0.2989,  4.2807,  0.2203,  0.0898]])
tensor([[-0.9018, -1.0821, -3.3580,  0